[package]
name = "project_euler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
dashu = "0.4.2"
num-prime = "0.4.4"
num-traits = "0.2.19"
paste = "1.0.15"
permutohedron = "0.2.4"

[profile.release]
opt-level = 3
lto = true
