[package]
name = "project_euler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
dashu = "0.4.2"
num-prime = "0.4.4"
paste = "1.0.15"
phf = { version = "0.11.2", features = ["macros"] }

[profile.release]
opt-level = 3
lto = true
